/*
 * GMO Aozora Net Bank Open API
 * <p>Ph2.5向けに作成したもの</p> 
 *
 * OpenAPI spec version: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package webhook.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Objects;

/**
 * 入金口座情報 
 */
@ApiModel(description = "入金口座情報 ")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-11T10:04:38.046Z")
public class Account implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("raId")
  private String raId = null;

  @SerializedName("raBranchCode")
  private String raBranchCode = null;

  @SerializedName("raBranchNameKana")
  private String raBranchNameKana = null;

  @SerializedName("raAccountNumber")
  private String raAccountNumber = null;

  @SerializedName("raHolderName")
  private String raHolderName = null;

  @SerializedName("baseDate")
  private String baseDate = null;

  @SerializedName("baseTime")
  private String baseTime = null;

  public Account raId(String raId) {
    this.raId = raId;
    return this;
  }

   /**
   * 入金口座ID 半角数字 入金先の口座を識別するID 
   * @return raId
  **/
  @ApiModelProperty(example = "201011234567", required = true, value = "入金口座ID 半角数字 入金先の口座を識別するID ")
  public String getRaId() {
    return raId;
  }

  public void setRaId(String raId) {
    this.raId = raId;
  }

  public Account raBranchCode(String raBranchCode) {
    this.raBranchCode = raBranchCode;
    return this;
  }

   /**
   * 入金口座　支店コード 半角数字 
   * @return raBranchCode
  **/
  @ApiModelProperty(example = "201", required = true, value = "入金口座　支店コード 半角数字 ")
  public String getRaBranchCode() {
    return raBranchCode;
  }

  public void setRaBranchCode(String raBranchCode) {
    this.raBranchCode = raBranchCode;
  }

  public Account raBranchNameKana(String raBranchNameKana) {
    this.raBranchNameKana = raBranchNameKana;
    return this;
  }

   /**
   * 半角文字 
   * @return raBranchNameKana
  **/
  @ApiModelProperty(example = "ﾋﾞｼﾞﾈｽ", required = true, value = "半角文字 ")
  public String getRaBranchNameKana() {
    return raBranchNameKana;
  }

  public void setRaBranchNameKana(String raBranchNameKana) {
    this.raBranchNameKana = raBranchNameKana;
  }

  public Account raAccountNumber(String raAccountNumber) {
    this.raAccountNumber = raAccountNumber;
    return this;
  }

   /**
   * 半角数字 
   * @return raAccountNumber
  **/
  @ApiModelProperty(example = "1234567", required = true, value = "半角数字 ")
  public String getRaAccountNumber() {
    return raAccountNumber;
  }

  public void setRaAccountNumber(String raAccountNumber) {
    this.raAccountNumber = raAccountNumber;
  }

  public Account raHolderName(String raHolderName) {
    this.raHolderName = raHolderName;
    return this;
  }

   /**
   * 全角文字 
   * @return raHolderName
  **/
  @ApiModelProperty(example = "ＧＭＯ　あおぞら　太郎", required = true, value = "全角文字 ")
  public String getRaHolderName() {
    return raHolderName;
  }

  public void setRaHolderName(String raHolderName) {
    this.raHolderName = raHolderName;
  }

  public Account baseDate(String baseDate) {
    this.baseDate = baseDate;
    return this;
  }

   /**
   * 基準日 半角文字 応答日付、もしくは入金明細の基準日を示す。 YYYY-MM-DD形式 
   * @return baseDate
  **/
  @ApiModelProperty(example = "2018-08-10", required = true, value = "基準日 半角文字 応答日付、もしくは入金明細の基準日を示す。 YYYY-MM-DD形式 ")
  public String getBaseDate() {
    return baseDate;
  }

  public void setBaseDate(String baseDate) {
    this.baseDate = baseDate;
  }

  public Account baseTime(String baseTime) {
    this.baseTime = baseTime;
    return this;
  }

   /**
   * 基準時刻 半角文字 応答時刻、もしくは入金明細の基準時刻を示す。  ISO8601 時差(offset)も表記 HH:MM:SS+09:00形式 
   * @return baseTime
  **/
  @ApiModelProperty(example = "10:00:00+09:00", required = true, value = "基準時刻 半角文字 応答時刻、もしくは入金明細の基準時刻を示す。  ISO8601 時差(offset)も表記 HH:MM:SS+09:00形式 ")
  public String getBaseTime() {
    return baseTime;
  }

  public void setBaseTime(String baseTime) {
    this.baseTime = baseTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.raId, account.raId) &&
        Objects.equals(this.raBranchCode, account.raBranchCode) &&
        Objects.equals(this.raBranchNameKana, account.raBranchNameKana) &&
        Objects.equals(this.raAccountNumber, account.raAccountNumber) &&
        Objects.equals(this.raHolderName, account.raHolderName) &&
        Objects.equals(this.baseDate, account.baseDate) &&
        Objects.equals(this.baseTime, account.baseTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(raId, raBranchCode, raBranchNameKana, raAccountNumber, raHolderName, baseDate, baseTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");
    
    sb.append("    raId: ").append(toIndentedString(raId)).append("\n");
    sb.append("    raBranchCode: ").append(toIndentedString(raBranchCode)).append("\n");
    sb.append("    raBranchNameKana: ").append(toIndentedString(raBranchNameKana)).append("\n");
    sb.append("    raAccountNumber: ").append(toIndentedString(raAccountNumber)).append("\n");
    sb.append("    raHolderName: ").append(toIndentedString(raHolderName)).append("\n");
    sb.append("    baseDate: ").append(toIndentedString(baseDate)).append("\n");
    sb.append("    baseTime: ").append(toIndentedString(baseTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

