/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package corporate.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * TransferApply
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class TransferApply {
  @SerializedName("applyNo")
  private String applyNo = null;

  @SerializedName("transferApplyDetails")
  private List<TransferApplyDetail> transferApplyDetails = null;

  public TransferApply applyNo(String applyNo) {
    this.applyNo = applyNo;
    return this;
  }

   /**
   * 受付番号（振込申請番号） 半角数字 すべての振込・総合振込で採番される、照会の基本単位となる番号
   * @return applyNo
  **/
  @ApiModelProperty(example = "2018072902345678", value = "受付番号（振込申請番号） 半角数字 すべての振込・総合振込で採番される、照会の基本単位となる番号 ")
  public String getApplyNo() {
    return applyNo;
  }

  public void setApplyNo(String applyNo) {
    this.applyNo = applyNo;
  }

  public TransferApply transferApplyDetails(List<TransferApplyDetail> transferApplyDetails) {
    this.transferApplyDetails = transferApplyDetails;
    return this;
  }

  public TransferApply addTransferApplyDetailsItem(TransferApplyDetail transferApplyDetailsItem) {
    if (this.transferApplyDetails == null) {
      this.transferApplyDetails = new ArrayList<>();
    }
    this.transferApplyDetails.add(transferApplyDetailsItem);
    return this;
  }

   /**
   * 振込申請詳細情報 振込申請詳細情報のリスト 該当する情報が無い場合は空のリストを返却
   * @return transferApplyDetails
  **/
  @ApiModelProperty(value = "振込申請詳細情報 振込申請詳細情報のリスト 該当する情報が無い場合は空のリストを返却 ")
  public List<TransferApplyDetail> getTransferApplyDetails() {
    return transferApplyDetails;
  }

  public void setTransferApplyDetails(List<TransferApplyDetail> transferApplyDetails) {
    this.transferApplyDetails = transferApplyDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferApply transferApply = (TransferApply) o;
    return Objects.equals(this.applyNo, transferApply.applyNo) &&
        Objects.equals(this.transferApplyDetails, transferApply.transferApplyDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applyNo, transferApplyDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferApply {\n");

    sb.append("    applyNo: ").append(toIndentedString(applyNo)).append("\n");
    sb.append("    transferApplyDetails: ").append(toIndentedString(transferApplyDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

