/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package corporate.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * TransferDetailResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class TransferDetailResponse {
  @SerializedName("beneficiaryBankNameKanji")
  private String beneficiaryBankNameKanji = null;

  @SerializedName("beneficiaryBranchNameKanji")
  private String beneficiaryBranchNameKanji = null;

  @SerializedName("usedPoint")
  private String usedPoint = null;

  @SerializedName("isFeeFreeUsed")
  private Boolean isFeeFreeUsed = null;

  @SerializedName("transferFee")
  private String transferFee = null;

  public TransferDetailResponse beneficiaryBankNameKanji(String beneficiaryBankNameKanji) {
    this.beneficiaryBankNameKanji = beneficiaryBankNameKanji;
    return this;
  }

   /**
   * 被仕向金融機関名漢字 全角文字 被仕向金融機関番号に該当する金融機関名漢字 該当する情報が無い場合はNULLを返却 
   * @return beneficiaryBankNameKanji
  **/
  @ApiModelProperty(example = "あおぞら銀行", value = "被仕向金融機関名漢字 全角文字 被仕向金融機関番号に該当する金融機関名漢字 該当する情報が無い場合はNULLを返却 ")
  public String getBeneficiaryBankNameKanji() {
    return beneficiaryBankNameKanji;
  }

  public void setBeneficiaryBankNameKanji(String beneficiaryBankNameKanji) {
    this.beneficiaryBankNameKanji = beneficiaryBankNameKanji;
  }

  public TransferDetailResponse beneficiaryBranchNameKanji(String beneficiaryBranchNameKanji) {
    this.beneficiaryBranchNameKanji = beneficiaryBranchNameKanji;
    return this;
  }

   /**
   * 被仕向支店名漢字 全角文字 被仕向支店番号に該当する支店名漢字 該当する情報が無い場合はNULLを返却 
   * @return beneficiaryBranchNameKanji
  **/
  @ApiModelProperty(example = "本店", value = "被仕向支店名漢字 全角文字 被仕向支店番号に該当する支店名漢字 該当する情報が無い場合はNULLを返却 ")
  public String getBeneficiaryBranchNameKanji() {
    return beneficiaryBranchNameKanji;
  }

  public void setBeneficiaryBranchNameKanji(String beneficiaryBranchNameKanji) {
    this.beneficiaryBranchNameKanji = beneficiaryBranchNameKanji;
  }

  public TransferDetailResponse usedPoint(String usedPoint) {
    this.usedPoint = usedPoint;
    return this;
  }

   /**
   * 利用ポイント 半角数字 実際に利用したポイント 該当する情報が無い場合はNULLを返却 
   * @return usedPoint
  **/
  @ApiModelProperty(example = "1000", value = "利用ポイント 半角数字 実際に利用したポイント 該当する情報が無い場合はNULLを返却 ")
  public String getUsedPoint() {
    return usedPoint;
  }

  public void setUsedPoint(String usedPoint) {
    this.usedPoint = usedPoint;
  }

  public TransferDetailResponse isFeeFreeUsed(Boolean isFeeFreeUsed) {
    this.isFeeFreeUsed = isFeeFreeUsed;
    return this;
  }

   /**
   * 振込無料回数利用有無 振込無料回数の実際の利用有無 
   * @return isFeeFreeUsed
  **/
  @ApiModelProperty(example = "true", value = "振込無料回数利用有無 振込無料回数の実際の利用有無 ")
  public Boolean isIsFeeFreeUsed() {
    return isFeeFreeUsed;
  }

  public void setIsFeeFreeUsed(Boolean isFeeFreeUsed) {
    this.isFeeFreeUsed = isFeeFreeUsed;
  }

  public TransferDetailResponse transferFee(String transferFee) {
    this.transferFee = transferFee;
    return this;
  }

   /**
   * 手数料 半角数字 個別明細単位の手数料 該当する情報が無い場合はNULLを返却 
   * @return transferFee
  **/
  @ApiModelProperty(example = "1000", value = "手数料 半角数字 個別明細単位の手数料 該当する情報が無い場合はNULLを返却 ")
  public String getTransferFee() {
    return transferFee;
  }

  public void setTransferFee(String transferFee) {
    this.transferFee = transferFee;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferDetailResponse transferDetailResponse = (TransferDetailResponse) o;
    return Objects.equals(this.beneficiaryBankNameKanji, transferDetailResponse.beneficiaryBankNameKanji) &&
        Objects.equals(this.beneficiaryBranchNameKanji, transferDetailResponse.beneficiaryBranchNameKanji) &&
        Objects.equals(this.usedPoint, transferDetailResponse.usedPoint) &&
        Objects.equals(this.isFeeFreeUsed, transferDetailResponse.isFeeFreeUsed) &&
        Objects.equals(this.transferFee, transferDetailResponse.transferFee);
  }

  @Override
  public int hashCode() {
    return Objects.hash(beneficiaryBankNameKanji, beneficiaryBranchNameKanji, usedPoint, isFeeFreeUsed, transferFee);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferDetailResponse {\n");

    sb.append("    beneficiaryBankNameKanji: ").append(toIndentedString(beneficiaryBankNameKanji)).append("\n");
    sb.append("    beneficiaryBranchNameKanji: ").append(toIndentedString(beneficiaryBranchNameKanji)).append("\n");
    sb.append("    usedPoint: ").append(toIndentedString(usedPoint)).append("\n");
    sb.append("    isFeeFreeUsed: ").append(toIndentedString(isFeeFreeUsed)).append("\n");
    sb.append("    transferFee: ").append(toIndentedString(transferFee)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

