/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package corporate.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * Transfer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class Transfer {
  @SerializedName("itemId")
  private String itemId = null;

  @SerializedName("transferAmount")
  private String transferAmount = null;

  @SerializedName("ediInfo")
  private String ediInfo = null;

  @SerializedName("beneficiaryBankCode")
  private String beneficiaryBankCode = null;

  @SerializedName("beneficiaryBankName")
  private String beneficiaryBankName = null;

  @SerializedName("beneficiaryBranchCode")
  private String beneficiaryBranchCode = null;

  @SerializedName("beneficiaryBranchName")
  private String beneficiaryBranchName = null;

  @SerializedName("accountTypeCode")
  private String accountTypeCode = null;

  @SerializedName("accountNumber")
  private String accountNumber = null;

  @SerializedName("beneficiaryName")
  private String beneficiaryName = null;

  public Transfer itemId(String itemId) {
    this.itemId = itemId;
    return this;
  }

   /**
   * 明細番号 半角数字 重複/0はエラー　1～99とします 1件のみの場合は省略可（項目自体を設定しません） 
   * @return itemId
  **/
  @ApiModelProperty(example = "4", value = "明細番号 半角数字 重複/0はエラー　1～99とします 1件のみの場合は省略可（項目自体を設定しません） ")
  public String getItemId() {
    return itemId;
  }

  public void setItemId(String itemId) {
    this.itemId = itemId;
  }

  public Transfer transferAmount(String transferAmount) {
    this.transferAmount = transferAmount;
    return this;
  }

   /**
   * 振込金額 半角数字 1以上、整数のみ 
   * @return transferAmount
  **/
  @ApiModelProperty(example = "1000", required = true, value = "振込金額 半角数字 1以上、整数のみ ")
  public String getTransferAmount() {
    return transferAmount;
  }

  public void setTransferAmount(String transferAmount) {
    this.transferAmount = transferAmount;
  }

  public Transfer ediInfo(String ediInfo) {
    this.ediInfo = ediInfo;
    return this;
  }

   /**
   * EDI情報 半角文字 振込許容文字を指定可 
   * @return ediInfo
  **/
  @ApiModelProperty(example = "ｾｲｷｭｳｼｮﾊﾞﾝｺﾞｳ1234", value = "EDI情報 半角文字 振込許容文字を指定可 ")
  public String getEdiInfo() {
    return ediInfo;
  }

  public void setEdiInfo(String ediInfo) {
    this.ediInfo = ediInfo;
  }

  public Transfer beneficiaryBankCode(String beneficiaryBankCode) {
    this.beneficiaryBankCode = beneficiaryBankCode;
    return this;
  }

   /**
   * 被仕向金融機関番号 半角数字 
   * @return beneficiaryBankCode
  **/
  @ApiModelProperty(example = "0398", required = true, value = "被仕向金融機関番号 半角数字 ")
  public String getBeneficiaryBankCode() {
    return beneficiaryBankCode;
  }

  public void setBeneficiaryBankCode(String beneficiaryBankCode) {
    this.beneficiaryBankCode = beneficiaryBankCode;
  }

  public Transfer beneficiaryBankName(String beneficiaryBankName) {
    this.beneficiaryBankName = beneficiaryBankName;
    return this;
  }

   /**
   * 被仕向金融機関名カナ 半角文字 参考値、処理に利用しません 
   * @return beneficiaryBankName
  **/
  @ApiModelProperty(example = "ｱｵｿﾞﾗ", value = "被仕向金融機関名カナ 半角文字 参考値、処理に利用しません ")
  public String getBeneficiaryBankName() {
    return beneficiaryBankName;
  }

  public void setBeneficiaryBankName(String beneficiaryBankName) {
    this.beneficiaryBankName = beneficiaryBankName;
  }

  public Transfer beneficiaryBranchCode(String beneficiaryBranchCode) {
    this.beneficiaryBranchCode = beneficiaryBranchCode;
    return this;
  }

   /**
   * 被仕向支店番号 半角数字 
   * @return beneficiaryBranchCode
  **/
  @ApiModelProperty(example = "111", required = true, value = "被仕向支店番号 半角数字 ")
  public String getBeneficiaryBranchCode() {
    return beneficiaryBranchCode;
  }

  public void setBeneficiaryBranchCode(String beneficiaryBranchCode) {
    this.beneficiaryBranchCode = beneficiaryBranchCode;
  }

  public Transfer beneficiaryBranchName(String beneficiaryBranchName) {
    this.beneficiaryBranchName = beneficiaryBranchName;
    return this;
  }

   /**
   * 被仕向支店名カナ 半角文字 参考値、処理に利用しません 
   * @return beneficiaryBranchName
  **/
  @ApiModelProperty(example = "ﾎﾝﾃﾝ", value = "被仕向支店名カナ 半角文字 参考値、処理に利用しません ")
  public String getBeneficiaryBranchName() {
    return beneficiaryBranchName;
  }

  public void setBeneficiaryBranchName(String beneficiaryBranchName) {
    this.beneficiaryBranchName = beneficiaryBranchName;
  }

  public Transfer accountTypeCode(String accountTypeCode) {
    this.accountTypeCode = accountTypeCode;
    return this;
  }

   /**
   * 科目コード（預金種別コード） 半角数字 1：普通、2：当座、4：貯蓄、9：その他 
   * @return accountTypeCode
  **/
  @ApiModelProperty(example = "1", required = true, value = "科目コード（預金種別コード） 半角数字 1：普通、2：当座、4：貯蓄、9：その他 ")
  public String getAccountTypeCode() {
    return accountTypeCode;
  }

  public void setAccountTypeCode(String accountTypeCode) {
    this.accountTypeCode = accountTypeCode;
  }

  public Transfer accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * 口座番号 半角数字 7桁未満の番号は右詰で、前ゼロで埋めること 
   * @return accountNumber
  **/
  @ApiModelProperty(example = "1234567", required = true, value = "口座番号 半角数字 7桁未満の番号は右詰で、前ゼロで埋めること ")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public Transfer beneficiaryName(String beneficiaryName) {
    this.beneficiaryName = beneficiaryName;
    return this;
  }

   /**
   * 受取人名 半角文字 振込許容文字を指定可 ただし、一部の非許容文字は、許容文字に変換を行う 
   * @return beneficiaryName
  **/
  @ApiModelProperty(example = "ｶ)ｱｵｿﾞﾗｻﾝｷﾞｮｳ", required = true, value = "受取人名 半角文字 振込許容文字を指定可 ただし、一部の非許容文字は、許容文字に変換を行う ")
  public String getBeneficiaryName() {
    return beneficiaryName;
  }

  public void setBeneficiaryName(String beneficiaryName) {
    this.beneficiaryName = beneficiaryName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transfer transfer = (Transfer) o;
    return Objects.equals(this.itemId, transfer.itemId) &&
        Objects.equals(this.transferAmount, transfer.transferAmount) &&
        Objects.equals(this.ediInfo, transfer.ediInfo) &&
        Objects.equals(this.beneficiaryBankCode, transfer.beneficiaryBankCode) &&
        Objects.equals(this.beneficiaryBankName, transfer.beneficiaryBankName) &&
        Objects.equals(this.beneficiaryBranchCode, transfer.beneficiaryBranchCode) &&
        Objects.equals(this.beneficiaryBranchName, transfer.beneficiaryBranchName) &&
        Objects.equals(this.accountTypeCode, transfer.accountTypeCode) &&
        Objects.equals(this.accountNumber, transfer.accountNumber) &&
        Objects.equals(this.beneficiaryName, transfer.beneficiaryName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemId, transferAmount, ediInfo, beneficiaryBankCode, beneficiaryBankName, beneficiaryBranchCode, beneficiaryBranchName, accountTypeCode, accountNumber, beneficiaryName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transfer {\n");

    sb.append("    itemId: ").append(toIndentedString(itemId)).append("\n");
    sb.append("    transferAmount: ").append(toIndentedString(transferAmount)).append("\n");
    sb.append("    ediInfo: ").append(toIndentedString(ediInfo)).append("\n");
    sb.append("    beneficiaryBankCode: ").append(toIndentedString(beneficiaryBankCode)).append("\n");
    sb.append("    beneficiaryBankName: ").append(toIndentedString(beneficiaryBankName)).append("\n");
    sb.append("    beneficiaryBranchCode: ").append(toIndentedString(beneficiaryBranchCode)).append("\n");
    sb.append("    beneficiaryBranchName: ").append(toIndentedString(beneficiaryBranchName)).append("\n");
    sb.append("    accountTypeCode: ").append(toIndentedString(accountTypeCode)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    beneficiaryName: ").append(toIndentedString(beneficiaryName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

