/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package corporate.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * Va
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class Va {
  @SerializedName("vaId")
  private String vaId = null;

  @SerializedName("vaBranchCode")
  private String vaBranchCode = null;

  @SerializedName("vaBranchNameKana")
  private String vaBranchNameKana = null;

  @SerializedName("vaAccountNumber")
  private String vaAccountNumber = null;

  public Va vaId(String vaId) {
    this.vaId = vaId;
    return this;
  }

   /**
   * 振込入金口座ID 半角数字 振込入金口座を識別するID 
   * @return vaId
  **/
  @ApiModelProperty(example = "5021099622", required = true, value = "振込入金口座ID 半角数字 振込入金口座を識別するID ")
  public String getVaId() {
    return vaId;
  }

  public void setVaId(String vaId) {
    this.vaId = vaId;
  }

  public Va vaBranchCode(String vaBranchCode) {
    this.vaBranchCode = vaBranchCode;
    return this;
  }

   /**
   * 支店コード 半角数字 
   * @return vaBranchCode
  **/
  @ApiModelProperty(example = "502", required = true, value = "支店コード 半角数字 ")
  public String getVaBranchCode() {
    return vaBranchCode;
  }

  public void setVaBranchCode(String vaBranchCode) {
    this.vaBranchCode = vaBranchCode;
  }

  public Va vaBranchNameKana(String vaBranchNameKana) {
    this.vaBranchNameKana = vaBranchNameKana;
    return this;
  }

   /**
   * 支店名カナ 半角文字 
   * @return vaBranchNameKana
  **/
  @ApiModelProperty(example = "ｱｼﾞｻｲ", required = true, value = "支店名カナ 半角文字 ")
  public String getVaBranchNameKana() {
    return vaBranchNameKana;
  }

  public void setVaBranchNameKana(String vaBranchNameKana) {
    this.vaBranchNameKana = vaBranchNameKana;
  }

  public Va vaAccountNumber(String vaAccountNumber) {
    this.vaAccountNumber = vaAccountNumber;
    return this;
  }

   /**
   * 口座番号 半角数字 
   * @return vaAccountNumber
  **/
  @ApiModelProperty(example = "1099622", required = true, value = "口座番号 半角数字 ")
  public String getVaAccountNumber() {
    return vaAccountNumber;
  }

  public void setVaAccountNumber(String vaAccountNumber) {
    this.vaAccountNumber = vaAccountNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Va va = (Va) o;
    return Objects.equals(this.vaId, va.vaId) &&
        Objects.equals(this.vaBranchCode, va.vaBranchCode) &&
        Objects.equals(this.vaBranchNameKana, va.vaBranchNameKana) &&
        Objects.equals(this.vaAccountNumber, va.vaAccountNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vaId, vaBranchCode, vaBranchNameKana, vaAccountNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Va {\n");

    sb.append("    vaId: ").append(toIndentedString(vaId)).append("\n");
    sb.append("    vaBranchCode: ").append(toIndentedString(vaBranchCode)).append("\n");
    sb.append("    vaBranchNameKana: ").append(toIndentedString(vaBranchNameKana)).append("\n");
    sb.append("    vaAccountNumber: ").append(toIndentedString(vaAccountNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

