/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package corporate.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * VaListRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class VaListRequest {
  @SerializedName("vaContractAuthKey")
  private String vaContractAuthKey = null;

  @SerializedName("vaTypeCode")
  private String vaTypeCode = null;

  @SerializedName("depositAmountExistCode")
  private String depositAmountExistCode = null;

  @SerializedName("vaHolderNameKana")
  private String vaHolderNameKana = null;

  @SerializedName("vaStatusCodeList")
  private List<VaStatusCode> vaStatusCodeList = null;

  @SerializedName("latestDepositDateFrom")
  private String latestDepositDateFrom = null;

  @SerializedName("latestDepositDateTo")
  private String latestDepositDateTo = null;

  @SerializedName("vaIssueDateFrom")
  private String vaIssueDateFrom = null;

  @SerializedName("vaIssueDateTo")
  private String vaIssueDateTo = null;

  @SerializedName("expireDateFrom")
  private String expireDateFrom = null;

  @SerializedName("expireDateTo")
  private String expireDateTo = null;

  @SerializedName("raId")
  private String raId = null;

  @SerializedName("nextItemKey")
  private String nextItemKey = null;

  @SerializedName("sortItemCode")
  private String sortItemCode = null;

  @SerializedName("sortOrderCode")
  private String sortOrderCode = null;

  @SerializedName("vaIdList")
  private List<VaId> vaIdList = null;

  public VaListRequest vaContractAuthKey(String vaContractAuthKey) {
    this.vaContractAuthKey = vaContractAuthKey;
    return this;
  }

   /**
   * 振込入金口座API認証情報 半角英数字 NULLを設定 値が設定されている場合は「400 Bad Request」を返却
   * @return vaContractAuthKey
  **/
  @ApiModelProperty(example = "5CSDFG1515A54DF", value = "振込入金口座API認証情報 半角英数字 NULLを設定 値が設定されている場合は「400 Bad Request」を返却 ")
  public String getVaContractAuthKey() {
    return vaContractAuthKey;
  }

  public void setVaContractAuthKey(String vaContractAuthKey) {
    this.vaContractAuthKey = vaContractAuthKey;
  }

  public VaListRequest vaTypeCode(String vaTypeCode) {
    this.vaTypeCode = vaTypeCode;
    return this;
  }

   /**
   * 振込入金口座　種類コード 半角数字 ・1&#x3D;期限型 ・2&#x3D;継続型
   * @return vaTypeCode
  **/
  @ApiModelProperty(example = "1", value = "振込入金口座　種類コード 半角数字 ・1=期限型 ・2=継続型 ")
  public String getVaTypeCode() {
    return vaTypeCode;
  }

  public void setVaTypeCode(String vaTypeCode) {
    this.vaTypeCode = vaTypeCode;
  }

  public VaListRequest depositAmountExistCode(String depositAmountExistCode) {
    this.depositAmountExistCode = depositAmountExistCode;
    return this;
  }

   /**
   * 入金有無コード 半角数字 ・1&#x3D;入金あり ・2&#x3D;入金なし
   * @return depositAmountExistCode
  **/
  @ApiModelProperty(example = "1", value = "入金有無コード 半角数字 ・1=入金あり ・2=入金なし ")
  public String getDepositAmountExistCode() {
    return depositAmountExistCode;
  }

  public void setDepositAmountExistCode(String depositAmountExistCode) {
    this.depositAmountExistCode = depositAmountExistCode;
  }

  public VaListRequest vaHolderNameKana(String vaHolderNameKana) {
    this.vaHolderNameKana = vaHolderNameKana;
    return this;
  }

   /**
   * 振込入金口座名義カナ 半角文字 振込許容文字を指定可 ただし、一部の非許容文字は、許容文字に変換を行う
   * @return vaHolderNameKana
  **/
  @ApiModelProperty(example = "ｼﾞｰｴﾑｵｰｱｵｿﾞﾗ(ｶ)ﾃｽﾄﾆｭｳｷﾝﾁ", value = "振込入金口座名義カナ 半角文字 振込許容文字を指定可 ただし、一部の非許容文字は、許容文字に変換を行う ")
  public String getVaHolderNameKana() {
    return vaHolderNameKana;
  }

  public void setVaHolderNameKana(String vaHolderNameKana) {
    this.vaHolderNameKana = vaHolderNameKana;
  }

  public VaListRequest vaStatusCodeList(List<VaStatusCode> vaStatusCodeList) {
    this.vaStatusCodeList = vaStatusCodeList;
    return this;
  }

  public VaListRequest addVaStatusCodeListItem(VaStatusCode vaStatusCodeListItem) {
    if (this.vaStatusCodeList == null) {
      this.vaStatusCodeList = new ArrayList<>();
    }
    this.vaStatusCodeList.add(vaStatusCodeListItem);
    return this;
  }

   /**
   * 振込入金口座IDリスト 照会したい振込入金口座状態コードのリスト 上限3件まで設定可能
   * @return vaStatusCodeList
  **/
  @ApiModelProperty(value = "振込入金口座IDリスト 照会したい振込入金口座状態コードのリスト 上限3件まで設定可能 ")
  public List<VaStatusCode> getVaStatusCodeList() {
    return vaStatusCodeList;
  }

  public void setVaStatusCodeList(List<VaStatusCode> vaStatusCodeList) {
    this.vaStatusCodeList = vaStatusCodeList;
  }

  public VaListRequest latestDepositDateFrom(String latestDepositDateFrom) {
    this.latestDepositDateFrom = latestDepositDateFrom;
    return this;
  }

   /**
   * 最終入金日From 半角文字 YYYY-MM-DD形式
   * @return latestDepositDateFrom
  **/
  @ApiModelProperty(example = "2018-08-10", value = "最終入金日From 半角文字 YYYY-MM-DD形式 ")
  public String getLatestDepositDateFrom() {
    return latestDepositDateFrom;
  }

  public void setLatestDepositDateFrom(String latestDepositDateFrom) {
    this.latestDepositDateFrom = latestDepositDateFrom;
  }

  public VaListRequest latestDepositDateTo(String latestDepositDateTo) {
    this.latestDepositDateTo = latestDepositDateTo;
    return this;
  }

   /**
   * 最終入金日To 半角文字 YYYY-MM-DD形式
   * @return latestDepositDateTo
  **/
  @ApiModelProperty(example = "2018-08-10", value = "最終入金日To 半角文字 YYYY-MM-DD形式 ")
  public String getLatestDepositDateTo() {
    return latestDepositDateTo;
  }

  public void setLatestDepositDateTo(String latestDepositDateTo) {
    this.latestDepositDateTo = latestDepositDateTo;
  }

  public VaListRequest vaIssueDateFrom(String vaIssueDateFrom) {
    this.vaIssueDateFrom = vaIssueDateFrom;
    return this;
  }

   /**
   * 振込入金口座発行日From 半角文字 YYYY-MM-DD形式
   * @return vaIssueDateFrom
  **/
  @ApiModelProperty(example = "2018-07-31", value = "振込入金口座発行日From 半角文字 YYYY-MM-DD形式 ")
  public String getVaIssueDateFrom() {
    return vaIssueDateFrom;
  }

  public void setVaIssueDateFrom(String vaIssueDateFrom) {
    this.vaIssueDateFrom = vaIssueDateFrom;
  }

  public VaListRequest vaIssueDateTo(String vaIssueDateTo) {
    this.vaIssueDateTo = vaIssueDateTo;
    return this;
  }

   /**
   * 振込入金口座発行日To 半角文字 YYYY-MM-DD形式
   * @return vaIssueDateTo
  **/
  @ApiModelProperty(example = "2018-08-01", value = "振込入金口座発行日To 半角文字 YYYY-MM-DD形式 ")
  public String getVaIssueDateTo() {
    return vaIssueDateTo;
  }

  public void setVaIssueDateTo(String vaIssueDateTo) {
    this.vaIssueDateTo = vaIssueDateTo;
  }

  public VaListRequest expireDateFrom(String expireDateFrom) {
    this.expireDateFrom = expireDateFrom;
    return this;
  }

   /**
   * 有効期限From 半角文字 YYYY-MM-DD形式
   * @return expireDateFrom
  **/
  @ApiModelProperty(example = "2018-08-31", value = "有効期限From 半角文字 YYYY-MM-DD形式 ")
  public String getExpireDateFrom() {
    return expireDateFrom;
  }

  public void setExpireDateFrom(String expireDateFrom) {
    this.expireDateFrom = expireDateFrom;
  }

  public VaListRequest expireDateTo(String expireDateTo) {
    this.expireDateTo = expireDateTo;
    return this;
  }

   /**
   * 有効期限To 半角文字 YYYY-MM-DD形式
   * @return expireDateTo
  **/
  @ApiModelProperty(example = "2018-09-01", value = "有効期限To 半角文字 YYYY-MM-DD形式 ")
  public String getExpireDateTo() {
    return expireDateTo;
  }

  public void setExpireDateTo(String expireDateTo) {
    this.expireDateTo = expireDateTo;
  }

  public VaListRequest raId(String raId) {
    this.raId = raId;
    return this;
  }

   /**
   * 入金先口座ID 半角数字 口座一覧照会APIで取得できる口座IDを設定
   * @return raId
  **/
  @ApiModelProperty(example = "101011234567", value = "入金先口座ID 半角数字 口座一覧照会APIで取得できる口座IDを設定 ")
  public String getRaId() {
    return raId;
  }

  public void setRaId(String raId) {
    this.raId = raId;
  }

  public VaListRequest nextItemKey(String nextItemKey) {
    this.nextItemKey = nextItemKey;
    return this;
  }

   /**
   * 次一覧キー 半角英数字
   * @return nextItemKey
  **/
  @ApiModelProperty(example = "AABA0515651", value = "次一覧キー 半角英数字 ")
  public String getNextItemKey() {
    return nextItemKey;
  }

  public void setNextItemKey(String nextItemKey) {
    this.nextItemKey = nextItemKey;
  }

  public VaListRequest sortItemCode(String sortItemCode) {
    this.sortItemCode = sortItemCode;
    return this;
  }

   /**
   * ソート項目コード 半角数字 ・1&#x3D;有効期限日時 ・2&#x3D;最終入金日 ・3&#x3D;発行日時 ・4&#x3D;最終入金金額
   * @return sortItemCode
  **/
  @ApiModelProperty(example = "2", value = "ソート項目コード 半角数字 ・1=有効期限日時 ・2=最終入金日 ・3=発行日時 ・4=最終入金金額 ")
  public String getSortItemCode() {
    return sortItemCode;
  }

  public void setSortItemCode(String sortItemCode) {
    this.sortItemCode = sortItemCode;
  }

  public VaListRequest sortOrderCode(String sortOrderCode) {
    this.sortOrderCode = sortOrderCode;
    return this;
  }

   /**
   * ソート順コード 半角数字 取引日のソート中を指定するコード値 ・1&#x3D;昇順 ・2&#x3D;降順
   * @return sortOrderCode
  **/
  @ApiModelProperty(example = "2", value = "ソート順コード 半角数字 取引日のソート中を指定するコード値 ・1=昇順 ・2=降順 ")
  public String getSortOrderCode() {
    return sortOrderCode;
  }

  public void setSortOrderCode(String sortOrderCode) {
    this.sortOrderCode = sortOrderCode;
  }

  public VaListRequest vaIdList(List<VaId> vaIdList) {
    this.vaIdList = vaIdList;
    return this;
  }

  public VaListRequest addVaIdListItem(VaId vaIdListItem) {
    if (this.vaIdList == null) {
      this.vaIdList = new ArrayList<>();
    }
    this.vaIdList.add(vaIdListItem);
    return this;
  }

   /**
   * 振込入金口座IDリスト 照会したい振込入金口座IDのリスト 上限500件まで設定可能
   * @return vaIdList
  **/
  @ApiModelProperty(value = "振込入金口座IDリスト 照会したい振込入金口座IDのリスト 上限500件まで設定可能 ")
  public List<VaId> getVaIdList() {
    return vaIdList;
  }

  public void setVaIdList(List<VaId> vaIdList) {
    this.vaIdList = vaIdList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VaListRequest vaListRequest = (VaListRequest) o;
    return Objects.equals(this.vaContractAuthKey, vaListRequest.vaContractAuthKey) &&
        Objects.equals(this.vaTypeCode, vaListRequest.vaTypeCode) &&
        Objects.equals(this.depositAmountExistCode, vaListRequest.depositAmountExistCode) &&
        Objects.equals(this.vaHolderNameKana, vaListRequest.vaHolderNameKana) &&
        Objects.equals(this.vaStatusCodeList, vaListRequest.vaStatusCodeList) &&
        Objects.equals(this.latestDepositDateFrom, vaListRequest.latestDepositDateFrom) &&
        Objects.equals(this.latestDepositDateTo, vaListRequest.latestDepositDateTo) &&
        Objects.equals(this.vaIssueDateFrom, vaListRequest.vaIssueDateFrom) &&
        Objects.equals(this.vaIssueDateTo, vaListRequest.vaIssueDateTo) &&
        Objects.equals(this.expireDateFrom, vaListRequest.expireDateFrom) &&
        Objects.equals(this.expireDateTo, vaListRequest.expireDateTo) &&
        Objects.equals(this.raId, vaListRequest.raId) &&
        Objects.equals(this.nextItemKey, vaListRequest.nextItemKey) &&
        Objects.equals(this.sortItemCode, vaListRequest.sortItemCode) &&
        Objects.equals(this.sortOrderCode, vaListRequest.sortOrderCode) &&
        Objects.equals(this.vaIdList, vaListRequest.vaIdList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vaContractAuthKey, vaTypeCode, depositAmountExistCode, vaHolderNameKana, vaStatusCodeList, latestDepositDateFrom, latestDepositDateTo, vaIssueDateFrom, vaIssueDateTo, expireDateFrom, expireDateTo, raId, nextItemKey, sortItemCode, sortOrderCode, vaIdList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VaListRequest {\n");

    sb.append("    vaContractAuthKey: ").append(toIndentedString(vaContractAuthKey)).append("\n");
    sb.append("    vaTypeCode: ").append(toIndentedString(vaTypeCode)).append("\n");
    sb.append("    depositAmountExistCode: ").append(toIndentedString(depositAmountExistCode)).append("\n");
    sb.append("    vaHolderNameKana: ").append(toIndentedString(vaHolderNameKana)).append("\n");
    sb.append("    vaStatusCodeList: ").append(toIndentedString(vaStatusCodeList)).append("\n");
    sb.append("    latestDepositDateFrom: ").append(toIndentedString(latestDepositDateFrom)).append("\n");
    sb.append("    latestDepositDateTo: ").append(toIndentedString(latestDepositDateTo)).append("\n");
    sb.append("    vaIssueDateFrom: ").append(toIndentedString(vaIssueDateFrom)).append("\n");
    sb.append("    vaIssueDateTo: ").append(toIndentedString(vaIssueDateTo)).append("\n");
    sb.append("    expireDateFrom: ").append(toIndentedString(expireDateFrom)).append("\n");
    sb.append("    expireDateTo: ").append(toIndentedString(expireDateTo)).append("\n");
    sb.append("    raId: ").append(toIndentedString(raId)).append("\n");
    sb.append("    nextItemKey: ").append(toIndentedString(nextItemKey)).append("\n");
    sb.append("    sortItemCode: ").append(toIndentedString(sortItemCode)).append("\n");
    sb.append("    sortOrderCode: ").append(toIndentedString(sortOrderCode)).append("\n");
    sb.append("    vaIdList: ").append(toIndentedString(vaIdList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

