/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package personal.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * SpAccountFcyBalance
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class SpAccountFcyBalance {
  @SerializedName("currencyCode")
  private String currencyCode = null;

  @SerializedName("currencyName")
  private String currencyName = null;

  @SerializedName("fcyTotalBalance")
  private String fcyTotalBalance = null;

  @SerializedName("ttb")
  private String ttb = null;

  @SerializedName("baseRateDate")
  private String baseRateDate = null;

  @SerializedName("baseRateTime")
  private String baseRateTime = null;

  @SerializedName("yenEquivalent")
  private String yenEquivalent = null;

  public SpAccountFcyBalance currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * 通貨コード 半角文字 ISO4217に準拠した通貨コード 
   * @return currencyCode
  **/
  @ApiModelProperty(example = "USD", required = true, value = "通貨コード 半角文字 ISO4217に準拠した通貨コード ")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public SpAccountFcyBalance currencyName(String currencyName) {
    this.currencyName = currencyName;
    return this;
  }

   /**
   * 通貨名 全角文字 ISO4217に準拠した通貨コードの当行での名称 
   * @return currencyName
  **/
  @ApiModelProperty(example = "米ドル", required = true, value = "通貨名 全角文字 ISO4217に準拠した通貨コードの当行での名称 ")
  public String getCurrencyName() {
    return currencyName;
  }

  public void setCurrencyName(String currencyName) {
    this.currencyName = currencyName;
  }

  public SpAccountFcyBalance fcyTotalBalance(String fcyTotalBalance) {
    this.fcyTotalBalance = fcyTotalBalance;
    return this;
  }

   /**
   * 外貨残高 半角数字　少数点および小数部最大3桁　マイナス含む 
   * @return fcyTotalBalance
  **/
  @ApiModelProperty(example = "350.48", required = true, value = "外貨残高 半角数字　少数点および小数部最大3桁　マイナス含む ")
  public String getFcyTotalBalance() {
    return fcyTotalBalance;
  }

  public void setFcyTotalBalance(String fcyTotalBalance) {
    this.fcyTotalBalance = fcyTotalBalance;
  }

  public SpAccountFcyBalance ttb(String ttb) {
    this.ttb = ttb;
    return this;
  }

   /**
   * 外貨レート 半角数字　少数点および小数部最大3桁　マイナス含む 
   * @return ttb
  **/
  @ApiModelProperty(example = "110.5", required = true, value = "外貨レート 半角数字　少数点および小数部最大3桁　マイナス含む ")
  public String getTtb() {
    return ttb;
  }

  public void setTtb(String ttb) {
    this.ttb = ttb;
  }

  public SpAccountFcyBalance baseRateDate(String baseRateDate) {
    this.baseRateDate = baseRateDate;
    return this;
  }

   /**
   * 外貨レート基準日 半角文字 外貨レートの基準日を示します YYYY-MM-DD形式 
   * @return baseRateDate
  **/
  @ApiModelProperty(example = "2018-08-10", required = true, value = "外貨レート基準日 半角文字 外貨レートの基準日を示します YYYY-MM-DD形式 ")
  public String getBaseRateDate() {
    return baseRateDate;
  }

  public void setBaseRateDate(String baseRateDate) {
    this.baseRateDate = baseRateDate;
  }

  public SpAccountFcyBalance baseRateTime(String baseRateTime) {
    this.baseRateTime = baseRateTime;
    return this;
  }

   /**
   * 外貨レート基準時刻 半角文字 外貨レートの基準時刻を示します HH:MM:SS+09:00形式 
   * @return baseRateTime
  **/
  @ApiModelProperty(example = "10:00:00+09:00", required = true, value = "外貨レート基準時刻 半角文字 外貨レートの基準時刻を示します HH:MM:SS+09:00形式 ")
  public String getBaseRateTime() {
    return baseRateTime;
  }

  public void setBaseRateTime(String baseRateTime) {
    this.baseRateTime = baseRateTime;
  }

  public SpAccountFcyBalance yenEquivalent(String yenEquivalent) {
    this.yenEquivalent = yenEquivalent;
    return this;
  }

   /**
   * 外貨円換算額 半角数字　マイナス含む 外貨残高を円に換算した額 
   * @return yenEquivalent
  **/
  @ApiModelProperty(example = "38728", required = true, value = "外貨円換算額 半角数字　マイナス含む 外貨残高を円に換算した額 ")
  public String getYenEquivalent() {
    return yenEquivalent;
  }

  public void setYenEquivalent(String yenEquivalent) {
    this.yenEquivalent = yenEquivalent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpAccountFcyBalance spAccountFcyBalance = (SpAccountFcyBalance) o;
    return Objects.equals(this.currencyCode, spAccountFcyBalance.currencyCode) &&
        Objects.equals(this.currencyName, spAccountFcyBalance.currencyName) &&
        Objects.equals(this.fcyTotalBalance, spAccountFcyBalance.fcyTotalBalance) &&
        Objects.equals(this.ttb, spAccountFcyBalance.ttb) &&
        Objects.equals(this.baseRateDate, spAccountFcyBalance.baseRateDate) &&
        Objects.equals(this.baseRateTime, spAccountFcyBalance.baseRateTime) &&
        Objects.equals(this.yenEquivalent, spAccountFcyBalance.yenEquivalent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currencyCode, currencyName, fcyTotalBalance, ttb, baseRateDate, baseRateTime, yenEquivalent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpAccountFcyBalance {\n");
    
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    currencyName: ").append(toIndentedString(currencyName)).append("\n");
    sb.append("    fcyTotalBalance: ").append(toIndentedString(fcyTotalBalance)).append("\n");
    sb.append("    ttb: ").append(toIndentedString(ttb)).append("\n");
    sb.append("    baseRateDate: ").append(toIndentedString(baseRateDate)).append("\n");
    sb.append("    baseRateTime: ").append(toIndentedString(baseRateTime)).append("\n");
    sb.append("    yenEquivalent: ").append(toIndentedString(yenEquivalent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

