/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package personal.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * SpAccountTransferResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class SpAccountTransferResponse {
  @SerializedName("acceptDatetime")
  private String acceptDatetime = null;

  @SerializedName("depositSpAccountId")
  private String depositSpAccountId = null;

  @SerializedName("debitSpAccountId")
  private String debitSpAccountId = null;

  @SerializedName("currencyCode")
  private String currencyCode = null;

  @SerializedName("currencyName")
  private String currencyName = null;

  @SerializedName("paymentAmount")
  private String paymentAmount = null;

  public SpAccountTransferResponse acceptDatetime(String acceptDatetime) {
    this.acceptDatetime = acceptDatetime;
    return this;
  }

   /**
   * 更新受付日時 更新を受付した銀行側の日時 
   * @return acceptDatetime
  **/
  @ApiModelProperty(example = "2018-08-01T10:00:00+09:00", value = "更新受付日時 更新を受付した銀行側の日時 ")
  public String getAcceptDatetime() {
    return acceptDatetime;
  }

  public void setAcceptDatetime(String acceptDatetime) {
    this.acceptDatetime = acceptDatetime;
  }

  public SpAccountTransferResponse depositSpAccountId(String depositSpAccountId) {
    this.depositSpAccountId = depositSpAccountId;
    return this;
  }

   /**
   * つかいわけ口座_入金口座ID 半角数字 口座を識別するID　入金先となる口座情報 
   * @return depositSpAccountId
  **/
  @ApiModelProperty(example = "101011234567", required = true, value = "つかいわけ口座_入金口座ID 半角数字 口座を識別するID　入金先となる口座情報 ")
  public String getDepositSpAccountId() {
    return depositSpAccountId;
  }

  public void setDepositSpAccountId(String depositSpAccountId) {
    this.depositSpAccountId = depositSpAccountId;
  }

  public SpAccountTransferResponse debitSpAccountId(String debitSpAccountId) {
    this.debitSpAccountId = debitSpAccountId;
    return this;
  }

   /**
   * つかいわけ口座_出金口座ID 半角数字 口座を識別するID　引き落とし元となる口座情報 
   * @return debitSpAccountId
  **/
  @ApiModelProperty(example = "201012345678", required = true, value = "つかいわけ口座_出金口座ID 半角数字 口座を識別するID　引き落とし元となる口座情報 ")
  public String getDebitSpAccountId() {
    return debitSpAccountId;
  }

  public void setDebitSpAccountId(String debitSpAccountId) {
    this.debitSpAccountId = debitSpAccountId;
  }

  public SpAccountTransferResponse currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * 通貨コード 半角文字 ISO4217準拠した通貨コード 
   * @return currencyCode
  **/
  @ApiModelProperty(example = "JPY", value = "通貨コード 半角文字 ISO4217準拠した通貨コード ")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public SpAccountTransferResponse currencyName(String currencyName) {
    this.currencyName = currencyName;
    return this;
  }

   /**
   * 通貨名 全角文字 ISO4217準拠した通貨コードの当行での名称 
   * @return currencyName
  **/
  @ApiModelProperty(example = "日本円", value = "通貨名 全角文字 ISO4217準拠した通貨コードの当行での名称 ")
  public String getCurrencyName() {
    return currencyName;
  }

  public void setCurrencyName(String currencyName) {
    this.currencyName = currencyName;
  }

  public SpAccountTransferResponse paymentAmount(String paymentAmount) {
    this.paymentAmount = paymentAmount;
    return this;
  }

   /**
   * 支払金額 数値のみでカンマ、マイナス不可　1以上であること 
   * @return paymentAmount
  **/
  @ApiModelProperty(example = "5000", value = "支払金額 数値のみでカンマ、マイナス不可　1以上であること ")
  public String getPaymentAmount() {
    return paymentAmount;
  }

  public void setPaymentAmount(String paymentAmount) {
    this.paymentAmount = paymentAmount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpAccountTransferResponse spAccountTransferResponse = (SpAccountTransferResponse) o;
    return Objects.equals(this.acceptDatetime, spAccountTransferResponse.acceptDatetime) &&
        Objects.equals(this.depositSpAccountId, spAccountTransferResponse.depositSpAccountId) &&
        Objects.equals(this.debitSpAccountId, spAccountTransferResponse.debitSpAccountId) &&
        Objects.equals(this.currencyCode, spAccountTransferResponse.currencyCode) &&
        Objects.equals(this.currencyName, spAccountTransferResponse.currencyName) &&
        Objects.equals(this.paymentAmount, spAccountTransferResponse.paymentAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acceptDatetime, depositSpAccountId, debitSpAccountId, currencyCode, currencyName, paymentAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpAccountTransferResponse {\n");
    
    sb.append("    acceptDatetime: ").append(toIndentedString(acceptDatetime)).append("\n");
    sb.append("    depositSpAccountId: ").append(toIndentedString(depositSpAccountId)).append("\n");
    sb.append("    debitSpAccountId: ").append(toIndentedString(debitSpAccountId)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    currencyName: ").append(toIndentedString(currencyName)).append("\n");
    sb.append("    paymentAmount: ").append(toIndentedString(paymentAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

