/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package personal.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * TransferFeeResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class TransferFeeResponse {
  @SerializedName("accountId")
  private String accountId = null;

  @SerializedName("baseDate")
  private String baseDate = null;

  @SerializedName("baseTime")
  private String baseTime = null;

  @SerializedName("totalFee")
  private String totalFee = null;

  @SerializedName("transferFeeDetails")
  private List<TransferFeeDetail> transferFeeDetails = new ArrayList<>();

  public TransferFeeResponse accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * 口座ID 半角英数字 口座を識別するID 
   * @return accountId
  **/
  @ApiModelProperty(example = "101011234567", required = true, value = "口座ID 半角英数字 口座を識別するID ")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public TransferFeeResponse baseDate(String baseDate) {
    this.baseDate = baseDate;
    return this;
  }

   /**
   * 基準日 応答日付、もしくは手数料計算を実施した基準日を示します YYYY-MM-DD形式 
   * @return baseDate
  **/
  @ApiModelProperty(example = "2018-08-10", required = true, value = "基準日 応答日付、もしくは手数料計算を実施した基準日を示します YYYY-MM-DD形式 ")
  public String getBaseDate() {
    return baseDate;
  }

  public void setBaseDate(String baseDate) {
    this.baseDate = baseDate;
  }

  public TransferFeeResponse baseTime(String baseTime) {
    this.baseTime = baseTime;
    return this;
  }

   /**
   * 基準時刻 応答時刻、もしくは手数料計算を実施した基準時刻を示します HH:MM:SS+09:00形式 
   * @return baseTime
  **/
  @ApiModelProperty(example = "10:00:00+09:00", required = true, value = "基準時刻 応答時刻、もしくは手数料計算を実施した基準時刻を示します HH:MM:SS+09:00形式 ")
  public String getBaseTime() {
    return baseTime;
  }

  public void setBaseTime(String baseTime) {
    this.baseTime = baseTime;
  }

  public TransferFeeResponse totalFee(String totalFee) {
    this.totalFee = totalFee;
    return this;
  }

   /**
   * 合計振込手数料 半角数字 手数料の合計額を表示 
   * @return totalFee
  **/
  @ApiModelProperty(example = "20000", required = true, value = "合計振込手数料 半角数字 手数料の合計額を表示 ")
  public String getTotalFee() {
    return totalFee;
  }

  public void setTotalFee(String totalFee) {
    this.totalFee = totalFee;
  }

  public TransferFeeResponse transferFeeDetails(List<TransferFeeDetail> transferFeeDetails) {
    this.transferFeeDetails = transferFeeDetails;
    return this;
  }

  public TransferFeeResponse addTransferFeeDetailsItem(TransferFeeDetail transferFeeDetailsItem) {
    this.transferFeeDetails.add(transferFeeDetailsItem);
    return this;
  }

   /**
   * 振込手数料明細情報 個別明細を設定 
   * @return transferFeeDetails
  **/
  @ApiModelProperty(required = true, value = "振込手数料明細情報 個別明細を設定 ")
  public List<TransferFeeDetail> getTransferFeeDetails() {
    return transferFeeDetails;
  }

  public void setTransferFeeDetails(List<TransferFeeDetail> transferFeeDetails) {
    this.transferFeeDetails = transferFeeDetails;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferFeeResponse transferFeeResponse = (TransferFeeResponse) o;
    return Objects.equals(this.accountId, transferFeeResponse.accountId) &&
        Objects.equals(this.baseDate, transferFeeResponse.baseDate) &&
        Objects.equals(this.baseTime, transferFeeResponse.baseTime) &&
        Objects.equals(this.totalFee, transferFeeResponse.totalFee) &&
        Objects.equals(this.transferFeeDetails, transferFeeResponse.transferFeeDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, baseDate, baseTime, totalFee, transferFeeDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferFeeResponse {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    baseDate: ").append(toIndentedString(baseDate)).append("\n");
    sb.append("    baseTime: ").append(toIndentedString(baseTime)).append("\n");
    sb.append("    totalFee: ").append(toIndentedString(totalFee)).append("\n");
    sb.append("    transferFeeDetails: ").append(toIndentedString(transferFeeDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

