/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package personal.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * VaDepositTransactionsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class VaDepositTransactionsResponse {
  @SerializedName("raId")
  private String raId = null;

  @SerializedName("raBranchCode")
  private String raBranchCode = null;

  @SerializedName("raBranchNameKana")
  private String raBranchNameKana = null;

  @SerializedName("raAccountNumber")
  private String raAccountNumber = null;

  @SerializedName("raHolderName")
  private String raHolderName = null;

  @SerializedName("dateFrom")
  private String dateFrom = null;

  @SerializedName("dateTo")
  private String dateTo = null;

  @SerializedName("baseDate")
  private String baseDate = null;

  @SerializedName("baseTime")
  private String baseTime = null;

  @SerializedName("hasNext")
  private Boolean hasNext = null;

  @SerializedName("nextItemKey")
  private String nextItemKey = null;

  @SerializedName("count")
  private String count = null;

  @SerializedName("vaTransactions")
  private List<VaTransaction> vaTransactions = null;

  public VaDepositTransactionsResponse raId(String raId) {
    this.raId = raId;
    return this;
  }

   /**
   * 入金先口座ID 半角数字 入金先の口座を識別するID 
   * @return raId
  **/
  @ApiModelProperty(example = "101011234567", required = true, value = "入金先口座ID 半角数字 入金先の口座を識別するID ")
  public String getRaId() {
    return raId;
  }

  public void setRaId(String raId) {
    this.raId = raId;
  }

  public VaDepositTransactionsResponse raBranchCode(String raBranchCode) {
    this.raBranchCode = raBranchCode;
    return this;
  }

   /**
   * 入金口座　支店コード 半角数字 
   * @return raBranchCode
  **/
  @ApiModelProperty(example = "101", required = true, value = "入金口座　支店コード 半角数字 ")
  public String getRaBranchCode() {
    return raBranchCode;
  }

  public void setRaBranchCode(String raBranchCode) {
    this.raBranchCode = raBranchCode;
  }

  public VaDepositTransactionsResponse raBranchNameKana(String raBranchNameKana) {
    this.raBranchNameKana = raBranchNameKana;
    return this;
  }

   /**
   * 入金口座　支店名カナ 半角文字 
   * @return raBranchNameKana
  **/
  @ApiModelProperty(example = "ﾎｳｼﾞﾝｴｲｷﾞﾖｳﾌﾞ", required = true, value = "入金口座　支店名カナ 半角文字 ")
  public String getRaBranchNameKana() {
    return raBranchNameKana;
  }

  public void setRaBranchNameKana(String raBranchNameKana) {
    this.raBranchNameKana = raBranchNameKana;
  }

  public VaDepositTransactionsResponse raAccountNumber(String raAccountNumber) {
    this.raAccountNumber = raAccountNumber;
    return this;
  }

   /**
   * 入金口座　口座番号 半角数字 
   * @return raAccountNumber
  **/
  @ApiModelProperty(example = "1234567", required = true, value = "入金口座　口座番号 半角数字 ")
  public String getRaAccountNumber() {
    return raAccountNumber;
  }

  public void setRaAccountNumber(String raAccountNumber) {
    this.raAccountNumber = raAccountNumber;
  }

  public VaDepositTransactionsResponse raHolderName(String raHolderName) {
    this.raHolderName = raHolderName;
    return this;
  }

   /**
   * 入金口座　口座名義（漢字） 全角文字 
   * @return raHolderName
  **/
  @ApiModelProperty(example = "GMOあおぞら株式会社", required = true, value = "入金口座　口座名義（漢字） 全角文字 ")
  public String getRaHolderName() {
    return raHolderName;
  }

  public void setRaHolderName(String raHolderName) {
    this.raHolderName = raHolderName;
  }

  public VaDepositTransactionsResponse dateFrom(String dateFrom) {
    this.dateFrom = dateFrom;
    return this;
  }

   /**
   * 対象期間From 半角文字 YYYY-MM-DD形式 
   * @return dateFrom
  **/
  @ApiModelProperty(example = "2018-08-01", required = true, value = "対象期間From 半角文字 YYYY-MM-DD形式 ")
  public String getDateFrom() {
    return dateFrom;
  }

  public void setDateFrom(String dateFrom) {
    this.dateFrom = dateFrom;
  }

  public VaDepositTransactionsResponse dateTo(String dateTo) {
    this.dateTo = dateTo;
    return this;
  }

   /**
   * 対象期間To 半角文字 YYYY-MM-DD形式 
   * @return dateTo
  **/
  @ApiModelProperty(example = "2018-08-02", required = true, value = "対象期間To 半角文字 YYYY-MM-DD形式 ")
  public String getDateTo() {
    return dateTo;
  }

  public void setDateTo(String dateTo) {
    this.dateTo = dateTo;
  }

  public VaDepositTransactionsResponse baseDate(String baseDate) {
    this.baseDate = baseDate;
    return this;
  }

   /**
   * 基準日 半角文字 入金明細を照会した基準日を示します 
   * @return baseDate
  **/
  @ApiModelProperty(example = "2018-08-10", required = true, value = "基準日 半角文字 入金明細を照会した基準日を示します ")
  public String getBaseDate() {
    return baseDate;
  }

  public void setBaseDate(String baseDate) {
    this.baseDate = baseDate;
  }

  public VaDepositTransactionsResponse baseTime(String baseTime) {
    this.baseTime = baseTime;
    return this;
  }

   /**
   * 基準時刻 半角文字 入金明細を照会した基準時刻を示します 
   * @return baseTime
  **/
  @ApiModelProperty(example = "10:00:00+09:00", required = true, value = "基準時刻 半角文字 入金明細を照会した基準時刻を示します ")
  public String getBaseTime() {
    return baseTime;
  }

  public void setBaseTime(String baseTime) {
    this.baseTime = baseTime;
  }

  public VaDepositTransactionsResponse hasNext(Boolean hasNext) {
    this.hasNext = hasNext;
    return this;
  }

   /**
   * 次明細フラグ ・true&#x3D;次明細あり ・false&#x3D;次明細なし 
   * @return hasNext
  **/
  @ApiModelProperty(example = "true", required = true, value = "次明細フラグ ・true=次明細あり ・false=次明細なし ")
  public Boolean isHasNext() {
    return hasNext;
  }

  public void setHasNext(Boolean hasNext) {
    this.hasNext = hasNext;
  }

  public VaDepositTransactionsResponse nextItemKey(String nextItemKey) {
    this.nextItemKey = nextItemKey;
    return this;
  }

   /**
   * 次明細キー 半角数字 次明細フラグがfalseの場合はNULL 
   * @return nextItemKey
  **/
  @ApiModelProperty(example = "20181012090520112541", value = "次明細キー 半角数字 次明細フラグがfalseの場合はNULL ")
  public String getNextItemKey() {
    return nextItemKey;
  }

  public void setNextItemKey(String nextItemKey) {
    this.nextItemKey = nextItemKey;
  }

  public VaDepositTransactionsResponse count(String count) {
    this.count = count;
    return this;
  }

   /**
   * 明細取得件数 半角数字 
   * @return count
  **/
  @ApiModelProperty(example = "500", required = true, value = "明細取得件数 半角数字 ")
  public String getCount() {
    return count;
  }

  public void setCount(String count) {
    this.count = count;
  }

  public VaDepositTransactionsResponse vaTransactions(List<VaTransaction> vaTransactions) {
    this.vaTransactions = vaTransactions;
    return this;
  }

  public VaDepositTransactionsResponse addVaTransactionsItem(VaTransaction vaTransactionsItem) {
    if (this.vaTransactions == null) {
      this.vaTransactions = new ArrayList<>();
    }
    this.vaTransactions.add(vaTransactionsItem);
    return this;
  }

   /**
   * 振込入金口座入金明細情報リスト 該当する情報が無い場合は、空のリストを返却します 
   * @return vaTransactions
  **/
  @ApiModelProperty(value = "振込入金口座入金明細情報リスト 該当する情報が無い場合は、空のリストを返却します ")
  public List<VaTransaction> getVaTransactions() {
    return vaTransactions;
  }

  public void setVaTransactions(List<VaTransaction> vaTransactions) {
    this.vaTransactions = vaTransactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VaDepositTransactionsResponse vaDepositTransactionsResponse = (VaDepositTransactionsResponse) o;
    return Objects.equals(this.raId, vaDepositTransactionsResponse.raId) &&
        Objects.equals(this.raBranchCode, vaDepositTransactionsResponse.raBranchCode) &&
        Objects.equals(this.raBranchNameKana, vaDepositTransactionsResponse.raBranchNameKana) &&
        Objects.equals(this.raAccountNumber, vaDepositTransactionsResponse.raAccountNumber) &&
        Objects.equals(this.raHolderName, vaDepositTransactionsResponse.raHolderName) &&
        Objects.equals(this.dateFrom, vaDepositTransactionsResponse.dateFrom) &&
        Objects.equals(this.dateTo, vaDepositTransactionsResponse.dateTo) &&
        Objects.equals(this.baseDate, vaDepositTransactionsResponse.baseDate) &&
        Objects.equals(this.baseTime, vaDepositTransactionsResponse.baseTime) &&
        Objects.equals(this.hasNext, vaDepositTransactionsResponse.hasNext) &&
        Objects.equals(this.nextItemKey, vaDepositTransactionsResponse.nextItemKey) &&
        Objects.equals(this.count, vaDepositTransactionsResponse.count) &&
        Objects.equals(this.vaTransactions, vaDepositTransactionsResponse.vaTransactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(raId, raBranchCode, raBranchNameKana, raAccountNumber, raHolderName, dateFrom, dateTo, baseDate, baseTime, hasNext, nextItemKey, count, vaTransactions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VaDepositTransactionsResponse {\n");
    
    sb.append("    raId: ").append(toIndentedString(raId)).append("\n");
    sb.append("    raBranchCode: ").append(toIndentedString(raBranchCode)).append("\n");
    sb.append("    raBranchNameKana: ").append(toIndentedString(raBranchNameKana)).append("\n");
    sb.append("    raAccountNumber: ").append(toIndentedString(raAccountNumber)).append("\n");
    sb.append("    raHolderName: ").append(toIndentedString(raHolderName)).append("\n");
    sb.append("    dateFrom: ").append(toIndentedString(dateFrom)).append("\n");
    sb.append("    dateTo: ").append(toIndentedString(dateTo)).append("\n");
    sb.append("    baseDate: ").append(toIndentedString(baseDate)).append("\n");
    sb.append("    baseTime: ").append(toIndentedString(baseTime)).append("\n");
    sb.append("    hasNext: ").append(toIndentedString(hasNext)).append("\n");
    sb.append("    nextItemKey: ").append(toIndentedString(nextItemKey)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    vaTransactions: ").append(toIndentedString(vaTransactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

