/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package personal.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * VaIssueRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class VaIssueRequest {
  @SerializedName("vaTypeCode")
  private String vaTypeCode = null;

  @SerializedName("issueRequestCount")
  private String issueRequestCount = null;

  @SerializedName("raId")
  private String raId = null;

  @SerializedName("vaContractAuthKey")
  private String vaContractAuthKey = null;

  @SerializedName("vaHolderNameKana")
  private String vaHolderNameKana = null;

  @SerializedName("vaHolderNamePos")
  private String vaHolderNamePos = null;

  public VaIssueRequest vaTypeCode(String vaTypeCode) {
    this.vaTypeCode = vaTypeCode;
    return this;
  }

   /**
   * 振込入金口座　種類コード 半角数字 ・1&#x3D;期限型 ・2&#x3D;継続型 
   * @return vaTypeCode
  **/
  @ApiModelProperty(example = "1", required = true, value = "振込入金口座　種類コード 半角数字 ・1=期限型 ・2=継続型 ")
  public String getVaTypeCode() {
    return vaTypeCode;
  }

  public void setVaTypeCode(String vaTypeCode) {
    this.vaTypeCode = vaTypeCode;
  }

  public VaIssueRequest issueRequestCount(String issueRequestCount) {
    this.issueRequestCount = issueRequestCount;
    return this;
  }

   /**
   * 発行口座数 半角数字 1回のリクエストで1,000口座まで発行可能 
   * @return issueRequestCount
  **/
  @ApiModelProperty(example = "1000", required = true, value = "発行口座数 半角数字 1回のリクエストで1,000口座まで発行可能 ")
  public String getIssueRequestCount() {
    return issueRequestCount;
  }

  public void setIssueRequestCount(String issueRequestCount) {
    this.issueRequestCount = issueRequestCount;
  }

  public VaIssueRequest raId(String raId) {
    this.raId = raId;
    return this;
  }

   /**
   * 入金先口座ID 半角数字 科目コードが以下の口座IDのみ受け付けます ・01&#x3D;普通預金（有利息） ・02&#x3D;普通預金（決済用） 必須 
   * @return raId
  **/
  @ApiModelProperty(example = "101011234567", value = "入金先口座ID 半角数字 科目コードが以下の口座IDのみ受け付けます ・01=普通預金（有利息） ・02=普通預金（決済用） 必須 ")
  public String getRaId() {
    return raId;
  }

  public void setRaId(String raId) {
    this.raId = raId;
  }

  public VaIssueRequest vaContractAuthKey(String vaContractAuthKey) {
    this.vaContractAuthKey = vaContractAuthKey;
    return this;
  }

   /**
   * 振込入金口座API認証情報 半角英数字 NULLを設定 値が設定されている場合は「400 Bad Request」を返却 
   * @return vaContractAuthKey
  **/
  @ApiModelProperty(example = "5CSDFG1515A54DF", value = "振込入金口座API認証情報 半角英数字 NULLを設定 値が設定されている場合は「400 Bad Request」を返却 ")
  public String getVaContractAuthKey() {
    return vaContractAuthKey;
  }

  public void setVaContractAuthKey(String vaContractAuthKey) {
    this.vaContractAuthKey = vaContractAuthKey;
  }

  public VaIssueRequest vaHolderNameKana(String vaHolderNameKana) {
    this.vaHolderNameKana = vaHolderNameKana;
    return this;
  }

   /**
   * 追加名義カナ 半角カナ英数記号 口座名義カナの文字数 + 追加名義カナの文字数が40文字以内 ・使用可能な記号は「/」、「)」、「.」、「‐」 ・濁点、半濁点は１文字として数えます 
   * @return vaHolderNameKana
  **/
  @ApiModelProperty(example = "ﾃｽﾄﾆｭｳｷﾝｸﾞﾁ", value = "追加名義カナ 半角カナ英数記号 口座名義カナの文字数 + 追加名義カナの文字数が40文字以内 ・使用可能な記号は「/」、「)」、「.」、「‐」 ・濁点、半濁点は１文字として数えます ")
  public String getVaHolderNameKana() {
    return vaHolderNameKana;
  }

  public void setVaHolderNameKana(String vaHolderNameKana) {
    this.vaHolderNameKana = vaHolderNameKana;
  }

  public VaIssueRequest vaHolderNamePos(String vaHolderNamePos) {
    this.vaHolderNamePos = vaHolderNamePos;
    return this;
  }

   /**
   * 追加名義位置 半角数字 追加名義カナを口座名義の前につけるか後ろにつけるかの指定 ・1&#x3D;通常（後ろにつける） ・2&#x3D;前につける 指定が無い場合は後ろにつけます 
   * @return vaHolderNamePos
  **/
  @ApiModelProperty(example = "1", value = "追加名義位置 半角数字 追加名義カナを口座名義の前につけるか後ろにつけるかの指定 ・1=通常（後ろにつける） ・2=前につける 指定が無い場合は後ろにつけます ")
  public String getVaHolderNamePos() {
    return vaHolderNamePos;
  }

  public void setVaHolderNamePos(String vaHolderNamePos) {
    this.vaHolderNamePos = vaHolderNamePos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VaIssueRequest vaIssueRequest = (VaIssueRequest) o;
    return Objects.equals(this.vaTypeCode, vaIssueRequest.vaTypeCode) &&
        Objects.equals(this.issueRequestCount, vaIssueRequest.issueRequestCount) &&
        Objects.equals(this.raId, vaIssueRequest.raId) &&
        Objects.equals(this.vaContractAuthKey, vaIssueRequest.vaContractAuthKey) &&
        Objects.equals(this.vaHolderNameKana, vaIssueRequest.vaHolderNameKana) &&
        Objects.equals(this.vaHolderNamePos, vaIssueRequest.vaHolderNamePos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vaTypeCode, issueRequestCount, raId, vaContractAuthKey, vaHolderNameKana, vaHolderNamePos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VaIssueRequest {\n");
    
    sb.append("    vaTypeCode: ").append(toIndentedString(vaTypeCode)).append("\n");
    sb.append("    issueRequestCount: ").append(toIndentedString(issueRequestCount)).append("\n");
    sb.append("    raId: ").append(toIndentedString(raId)).append("\n");
    sb.append("    vaContractAuthKey: ").append(toIndentedString(vaContractAuthKey)).append("\n");
    sb.append("    vaHolderNameKana: ").append(toIndentedString(vaHolderNameKana)).append("\n");
    sb.append("    vaHolderNamePos: ").append(toIndentedString(vaHolderNamePos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

