/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package personal.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * VaListResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class VaListResponse {
  @SerializedName("baseDate")
  private String baseDate = null;

  @SerializedName("baseTime")
  private String baseTime = null;

  @SerializedName("hasNext")
  private Boolean hasNext = null;

  @SerializedName("nextItemKey")
  private String nextItemKey = null;

  @SerializedName("count")
  private String count = null;

  @SerializedName("vAccounts")
  private List<VAccount> vAccounts = null;

  public VaListResponse baseDate(String baseDate) {
    this.baseDate = baseDate;
    return this;
  }

   /**
   * 基準日 一覧照会の基準日を示します YYYY-MM-DD形式 
   * @return baseDate
  **/
  @ApiModelProperty(example = "2018-08-10", required = true, value = "基準日 一覧照会の基準日を示します YYYY-MM-DD形式 ")
  public String getBaseDate() {
    return baseDate;
  }

  public void setBaseDate(String baseDate) {
    this.baseDate = baseDate;
  }

  public VaListResponse baseTime(String baseTime) {
    this.baseTime = baseTime;
    return this;
  }

   /**
   * 基準時刻 一覧照会の基準時刻を示します HH:MM:SS+09:00形式 
   * @return baseTime
  **/
  @ApiModelProperty(example = "10:00:00+09:00", required = true, value = "基準時刻 一覧照会の基準時刻を示します HH:MM:SS+09:00形式 ")
  public String getBaseTime() {
    return baseTime;
  }

  public void setBaseTime(String baseTime) {
    this.baseTime = baseTime;
  }

  public VaListResponse hasNext(Boolean hasNext) {
    this.hasNext = hasNext;
    return this;
  }

   /**
   * 次一覧フラグ ・true&#x3D;次一覧あり ・false&#x3D;次一覧なし 
   * @return hasNext
  **/
  @ApiModelProperty(example = "true", required = true, value = "次一覧フラグ ・true=次一覧あり ・false=次一覧なし ")
  public Boolean isHasNext() {
    return hasNext;
  }

  public void setHasNext(Boolean hasNext) {
    this.hasNext = hasNext;
  }

  public VaListResponse nextItemKey(String nextItemKey) {
    this.nextItemKey = nextItemKey;
    return this;
  }

   /**
   * 次一覧キー 半角英数字 次一覧フラグがfalseの場合はNULL 
   * @return nextItemKey
  **/
  @ApiModelProperty(example = "AABA0515651", value = "次一覧キー 半角英数字 次一覧フラグがfalseの場合はNULL ")
  public String getNextItemKey() {
    return nextItemKey;
  }

  public void setNextItemKey(String nextItemKey) {
    this.nextItemKey = nextItemKey;
  }

  public VaListResponse count(String count) {
    this.count = count;
    return this;
  }

   /**
   * 口座取得件数 半角数字 
   * @return count
  **/
  @ApiModelProperty(example = "800", required = true, value = "口座取得件数 半角数字 ")
  public String getCount() {
    return count;
  }

  public void setCount(String count) {
    this.count = count;
  }

  public VaListResponse vAccounts(List<VAccount> vAccounts) {
    this.vAccounts = vAccounts;
    return this;
  }

  public VaListResponse addVAccountsItem(VAccount vAccountsItem) {
    if (this.vAccounts == null) {
      this.vAccounts = new ArrayList<>();
    }
    this.vAccounts.add(vAccountsItem);
    return this;
  }

   /**
   * 振込入金口座情報 振込入金口座情報のリスト 該当する情報が無い場合は空のリストを返却 
   * @return vAccounts
  **/
  @ApiModelProperty(value = "振込入金口座情報 振込入金口座情報のリスト 該当する情報が無い場合は空のリストを返却 ")
  public List<VAccount> getVAccounts() {
    return vAccounts;
  }

  public void setVAccounts(List<VAccount> vAccounts) {
    this.vAccounts = vAccounts;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VaListResponse vaListResponse = (VaListResponse) o;
    return Objects.equals(this.baseDate, vaListResponse.baseDate) &&
        Objects.equals(this.baseTime, vaListResponse.baseTime) &&
        Objects.equals(this.hasNext, vaListResponse.hasNext) &&
        Objects.equals(this.nextItemKey, vaListResponse.nextItemKey) &&
        Objects.equals(this.count, vaListResponse.count) &&
        Objects.equals(this.vAccounts, vaListResponse.vAccounts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseDate, baseTime, hasNext, nextItemKey, count, vAccounts);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VaListResponse {\n");
    
    sb.append("    baseDate: ").append(toIndentedString(baseDate)).append("\n");
    sb.append("    baseTime: ").append(toIndentedString(baseTime)).append("\n");
    sb.append("    hasNext: ").append(toIndentedString(hasNext)).append("\n");
    sb.append("    nextItemKey: ").append(toIndentedString(nextItemKey)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    vAccounts: ").append(toIndentedString(vAccounts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

