/*
 * GMO Aozora Net Bank Open API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package personal.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/**
 * VaStatusCode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-18T06:43:57.831Z")
public class VaStatusCode {
  @SerializedName("vaStatusCode")
  private String vaStatusCode = null;

  public VaStatusCode vaStatusCode(String vaStatusCode) {
    this.vaStatusCode = vaStatusCode;
    return this;
  }

   /**
   * 振込入金口座　状態コード 半角数字 ・1&#x3D;利用可能 ・2&#x3D;停止中 ・3&#x3D;削除済 
   * @return vaStatusCode
  **/
  @ApiModelProperty(example = "1", value = "振込入金口座　状態コード 半角数字 ・1=利用可能 ・2=停止中 ・3=削除済 ")
  public String getVaStatusCode() {
    return vaStatusCode;
  }

  public void setVaStatusCode(String vaStatusCode) {
    this.vaStatusCode = vaStatusCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VaStatusCode vaStatusCode = (VaStatusCode) o;
    return Objects.equals(this.vaStatusCode, vaStatusCode.vaStatusCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vaStatusCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VaStatusCode {\n");
    
    sb.append("    vaStatusCode: ").append(toIndentedString(vaStatusCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

